version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: dictionary
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    command: ["redis-server", "--requirepass", "admin123"]
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - db
